project:
  type: website
  render:
    - "*.qmd"
    - "workshops/*.qmd"
  resources: 
    - "assets/**"
    - "extra/**"
    - "libroadp/**"
    - "politicalds/**"
    - "r-uc-2020/**"
    - "imgs/**"
    - "tesseractgt/**"
    - "workshops/*"
website:
  title: "Andr√©s Cruz"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - research.qmd
      - teaching.qmd
      - software.qmd
      - cv.qmd
  search: false
  favicon: imgs/favicon.ico
  twitter-card: true
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true
    respect-user-color-scheme: true
execute:
  freeze: false